// Seznam slovenskih besed za igro branja (1. razred, 6 let).
// Merila: VELIKE tiskane črke, en nedvoumen emoji na besedo, imenovalnik ednine,
// samo črke slovenske abecede, razpon dolžin za tri težavnostne stopnje.
// Zlogovanje: eno jedro na zlog (a e i o u ali zložni r), pri sklopu soglasnikov
// gre v naslednji zlog samo zadnji soglasnik, digrafa LJ in NJ se ne razbijeta.

export const WORDS = [
  // --- kratke (3–4 črke) ---
  { w: "PES", e: "🐶", syl: ["PES"] },
  { w: "MIŠ", e: "🐭", syl: ["MIŠ"] },
  { w: "LEV", e: "🦁", syl: ["LEV"] },
  { w: "RAK", e: "🦀", syl: ["RAK"] },
  { w: "JEŽ", e: "🦔", syl: ["JEŽ"] },
  { w: "SIR", e: "🧀", syl: ["SIR"] },
  { w: "MED", e: "🍯", syl: ["MED"] },
  { w: "RIŽ", e: "🍚", syl: ["RIŽ"] },
  { w: "ČAJ", e: "🍵", syl: ["ČAJ"] },
  { w: "DEŽ", e: "🌧️", syl: ["DEŽ"] },
  { w: "URA", e: "⏰", syl: ["U", "RA"] },
  { w: "NOŽ", e: "🔪", syl: ["NOŽ"] },
  { w: "ŠAL", e: "🧣", syl: ["ŠAL"] },
  { w: "OKO", e: "👁️", syl: ["O", "KO"] },
  { w: "UHO", e: "👂", syl: ["U", "HO"] },
  { w: "NOS", e: "👃", syl: ["NOS"] },
  { w: "ZOB", e: "🦷", syl: ["ZOB"] },
  { w: "MUCA", e: "🐱", syl: ["MU", "CA"] },
  { w: "KONJ", e: "🐴", syl: ["KONJ"] },
  { w: "OVCA", e: "🐑", syl: ["OV", "CA"] },
  { w: "SLON", e: "🐘", syl: ["SLON"] },
  { w: "ŽABA", e: "🐸", syl: ["ŽA", "BA"] },
  { w: "KAČA", e: "🐍", syl: ["KA", "ČA"] },
  { w: "RIBA", e: "🐟", syl: ["RI", "BA"] },
  { w: "RACA", e: "🦆", syl: ["RA", "CA"] },
  { w: "KRUH", e: "🍞", syl: ["KRUH"] },
  { w: "PICA", e: "🍕", syl: ["PI", "CA"] },
  { w: "GOBA", e: "🍄", syl: ["GO", "BA"] },
  { w: "LUNA", e: "🌙", syl: ["LU", "NA"] },
  { w: "ROŽA", e: "🌼", syl: ["RO", "ŽA"] },
  { w: "HIŠA", e: "🏠", syl: ["HI", "ŠA"] },
  { w: "GRAD", e: "🏰", syl: ["GRAD"] },
  { w: "AVTO", e: "🚗", syl: ["AV", "TO"] },
  { w: "VLAK", e: "🚂", syl: ["VLAK"] },
  { w: "ROKA", e: "✋", syl: ["RO", "KA"] },
  { w: "NOGA", e: "🦵", syl: ["NO", "GA"] },
  { w: "SRCE", e: "❤️", syl: ["SR", "CE"] },
  { w: "ŽOGA", e: "⚽", syl: ["ŽO", "GA"] },
  { w: "ŠOLA", e: "🏫", syl: ["ŠO", "LA"] },
  { w: "FANT", e: "👦", syl: ["FANT"] },
  { w: "IGLA", e: "🪡", syl: ["IG", "LA"] },

  // --- srednje (5–6 črk) ---
  { w: "KRAVA", e: "🐄", syl: ["KRA", "VA"] },
  { w: "ZAJEC", e: "🐰", syl: ["ZA", "JEC"] },
  { w: "TIGER", e: "🐯", syl: ["TI", "GER"] },
  { w: "ŽELVA", e: "🐢", syl: ["ŽEL", "VA"] },
  { w: "JELEN", e: "🦌", syl: ["JE", "LEN"] },
  { w: "HRČEK", e: "🐹", syl: ["HR", "ČEK"] },
  { w: "KOKOŠ", e: "🐔", syl: ["KO", "KOŠ"] },
  { w: "ZEBRA", e: "🦓", syl: ["ZEB", "RA"] },
  { w: "JAJCE", e: "🥚", syl: ["JAJ", "CE"] },
  { w: "MLEKO", e: "🥛", syl: ["MLE", "KO"] },
  { w: "TORTA", e: "🎂", syl: ["TOR", "TA"] },
  { w: "ČESEN", e: "🧄", syl: ["ČE", "SEN"] },
  { w: "FIŽOL", e: "🫘", syl: ["FI", "ŽOL"] },
  { w: "SONCE", e: "☀️", syl: ["SON", "CE"] },
  { w: "OBLAK", e: "☁️", syl: ["OB", "LAK"] },
  { w: "OGENJ", e: "🔥", syl: ["O", "GENJ"] },
  { w: "DREVO", e: "🌳", syl: ["DRE", "VO"] },
  { w: "MORJE", e: "🌊", syl: ["MOR", "JE"] },
  { w: "VRATA", e: "🚪", syl: ["VRA", "TA"] },
  { w: "KLJUČ", e: "🔑", syl: ["KLJUČ"] },
  { w: "SVEČA", e: "🕯️", syl: ["SVE", "ČA"] },
  { w: "ŽLICA", e: "🥄", syl: ["ŽLI", "CA"] },
  { w: "ROBOT", e: "🤖", syl: ["RO", "BOT"] },
  { w: "VEDRO", e: "🪣", syl: ["VED", "RO"] },
  { w: "DENAR", e: "💰", syl: ["DE", "NAR"] },
  { w: "JEZIK", e: "👅", syl: ["JE", "ZIK"] },
  { w: "PUNCA", e: "👧", syl: ["PUN", "CA"] },
  { w: "ŠOTOR", e: "⛺", syl: ["ŠO", "TOR"] },
  { w: "BALON", e: "🎈", syl: ["BA", "LON"] },
  { w: "PRAŠIČ", e: "🐷", syl: ["PRA", "ŠIČ"] },
  { w: "ŽIRAFA", e: "🦒", syl: ["ŽI", "RA", "FA"] },
  { w: "MEDVED", e: "🐻", syl: ["MED", "VED"] },
  { w: "LISICA", e: "🦊", syl: ["LI", "SI", "CA"] },
  { w: "METULJ", e: "🦋", syl: ["ME", "TULJ"] },
  { w: "ČEBELA", e: "🐝", syl: ["ČE", "BE", "LA"] },
  { w: "HRUŠKA", e: "🍐", syl: ["HRUŠ", "KA"] },
  { w: "BANANA", e: "🍌", syl: ["BA", "NA", "NA"] },
  { w: "JAGODA", e: "🍓", syl: ["JA", "GO", "DA"] },
  { w: "ČEŠNJA", e: "🍒", syl: ["ČEŠ", "NJA"] },
  { w: "ANANAS", e: "🍍", syl: ["A", "NA", "NAS"] },
  { w: "ČEBULA", e: "🧅", syl: ["ČE", "BU", "LA"] },
  { w: "ZVEZDA", e: "⭐", syl: ["ZVEZ", "DA"] },
  { w: "SMREKA", e: "🌲", syl: ["SMRE", "KA"] },
  { w: "ZEMLJA", e: "🌍", syl: ["ZEM", "LJA"] },
  { w: "VULKAN", e: "🌋", syl: ["VUL", "KAN"] },
  { w: "KNJIGA", e: "📕", syl: ["KNJI", "GA"] },
  { w: "ŠKARJE", e: "✂️", syl: ["ŠKAR", "JE"] },
  { w: "RAKETA", e: "🚀", syl: ["RA", "KE", "TA"] },
  { w: "LETALO", e: "✈️", syl: ["LE", "TA", "LO"] },
  { w: "DEŽNIK", e: "☂️", syl: ["DEŽ", "NIK"] },
  { w: "ČEVELJ", e: "👞", syl: ["ČE", "VELJ"] },
  { w: "KITARA", e: "🎸", syl: ["KI", "TA", "RA"] },
  { w: "CERKEV", e: "⛪", syl: ["CER", "KEV"] },
  { w: "CIRKUS", e: "🎪", syl: ["CIR", "KUS"] },
  { w: "BABICA", e: "👵", syl: ["BA", "BI", "CA"] },

  // --- daljše (7+ črk) ---
  { w: "MRAVLJA", e: "🐜", syl: ["MRAV", "LJA"] },
  { w: "PINGVIN", e: "🐧", syl: ["PING", "VIN"] },
  { w: "PETELIN", e: "🐓", syl: ["PE", "TE", "LIN"] },
  { w: "KENGURU", e: "🦘", syl: ["KEN", "GU", "RU"] },
  { w: "NOSOROG", e: "🦏", syl: ["NO", "SO", "ROG"] },
  { w: "NETOPIR", e: "🦇", syl: ["NE", "TO", "PIR"] },
  { w: "PIŠČANEC", e: "🐤", syl: ["PIŠ", "ČA", "NEC"] },
  { w: "KROKODIL", e: "🐊", syl: ["KRO", "KO", "DIL"] },
  { w: "VEVERICA", e: "🐿️", syl: ["VE", "VE", "RI", "CA"] },
  { w: "HOBOTNICA", e: "🐙", syl: ["HO", "BOT", "NI", "CA"] },
  { w: "DINOZAVER", e: "🦕", syl: ["DI", "NO", "ZA", "VER"] },
  { w: "JABOLKO", e: "🍎", syl: ["JA", "BOL", "KO"] },
  { w: "KORENJE", e: "🥕", syl: ["KO", "RE", "NJE"] },
  { w: "KROMPIR", e: "🥔", syl: ["KROM", "PIR"] },
  { w: "SENDVIČ", e: "🥪", syl: ["SEND", "VIČ"] },
  { w: "LUBENICA", e: "🍉", syl: ["LU", "BE", "NI", "CA"] },
  { w: "SLADOLED", e: "🍦", syl: ["SLA", "DO", "LED"] },
  { w: "ČOKOLADA", e: "🍫", syl: ["ČO", "KO", "LA", "DA"] },
  { w: "POMARANČA", e: "🍊", syl: ["PO", "MA", "RAN", "ČA"] },
  { w: "HAMBURGER", e: "🍔", syl: ["HAM", "BUR", "GER"] },
  { w: "PALAČINKA", e: "🥞", syl: ["PA", "LA", "ČIN", "KA"] },
  { w: "PARADIŽNIK", e: "🍅", syl: ["PA", "RA", "DIŽ", "NIK"] },
  { w: "MAVRICA", e: "🌈", syl: ["MAV", "RI", "CA"] },
  { w: "TULIPAN", e: "🌷", syl: ["TU", "LI", "PAN"] },
  { w: "SONČNICA", e: "🌻", syl: ["SONČ", "NI", "CA"] },
  { w: "TELEFON", e: "📱", syl: ["TE", "LE", "FON"] },
  { w: "TRAKTOR", e: "🚜", syl: ["TRAK", "TOR"] },
  { w: "AVTOBUS", e: "🚌", syl: ["AV", "TO", "BUS"] },
  { w: "ŽARNICA", e: "💡", syl: ["ŽAR", "NI", "CA"] },
  { w: "IZVIJAČ", e: "🪛", syl: ["IZ", "VI", "JAČ"] },
  { w: "MOŽGANI", e: "🧠", syl: ["MOŽ", "GA", "NI"] },
  { w: "POSTELJA", e: "🛏️", syl: ["POS", "TE", "LJA"] },
  { w: "SVINČNIK", e: "✏️", syl: ["SVINČ", "NIK"] },
  { w: "DOJENČEK", e: "👶", syl: ["DO", "JEN", "ČEK"] },
  { w: "NAHRBTNIK", e: "🎒", syl: ["NA", "HRBT", "NIK"] },
  { w: "ZEMLJEVID", e: "🗺️", syl: ["ZEM", "LJE", "VID"] },
  { w: "FOTOAPARAT", e: "📷", syl: ["FO", "TO", "A", "PA", "RAT"] },
  { w: "HELIKOPTER", e: "🚁", syl: ["HE", "LI", "KOP", "TER"] },
  { w: "RAČUNALNIK", e: "💻", syl: ["RA", "ČU", "NAL", "NIK"] },
  { w: "TELEVIZIJA", e: "📺", syl: ["TE", "LE", "VI", "ZI", "JA"] },
  { w: "KLJUČAVNICA", e: "🔒", syl: ["KLJU", "ČAV", "NI", "CA"] },
  { w: "EVRO", e: "💶", syl: ["EV", "RO"] },
];

/** Besede, dolge toliko črk ali manj — za lažje stopnje. */
export const wordsUpTo = (n) => WORDS.filter((x) => x.w.length <= n);
